# -*- coding: utf-8 -*-
"""fish-speech-colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8T3UM8ErBRYDDEnyZTQLMogb6r36lht

# fish-speech (s2-pro) WebUI on Google Colab

1. **Runtime → Change runtime type → T4 GPU (or better)** → Save
2. **Runtime → Run all** (Ctrl+F9)
3. Wait for install + model download (~10 min)
4. Open the `https://....gradio.live` link printed by the **last cell**

Note: the gradio link only works while the last cell is still running. Keep the Colab tab open.
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/fishaudio/fish-speech.git
# %cd fish-speech
!pip install -q uv
# pyaudio needs the portaudio C header to compile; it is only used by
# tools/api_client.py (speaker playback), not the webui
!apt-get update -q && apt-get install -y -q portaudio19-dev
!uv pip install --system -e ".[cu126]" || (sed -i '/pyaudio/d' pyproject.toml && uv pip install --system -e ".[cu126]")

pip install torchvision==0.23.0+cu126 --index-url https://download.pytorch.org/whl/cu126

# Download the s2-pro model (~11 GB) via the Python API (CLI is deprecated)
from huggingface_hub import snapshot_download
snapshot_download("fishaudio/s2-pro", local_dir="checkpoints/s2-pro")
print("download done")

# Make the web UI reachable from your browser (public gradio link)
!sed -i 's/app.launch()/app.launch(server_name="0.0.0.0", share=True)/' tools/run_webui.py
!grep -n "app.launch" tools/run_webui.py

import subprocess
import os

# Set environment variable to help with memory fragmentation
env = os.environ.copy()
env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# Start webui in background (does not block the notebook)
log = open("/content/webui.log", "w")
proc = subprocess.Popen(
    ["python", "tools/run_webui.py",
     "--llama-checkpoint-path", "checkpoints/s2-pro",
     "--decoder-checkpoint-path", "checkpoints/s2-pro/codec.pth",
     "--half"],
    stdout=log, stderr=subprocess.STDOUT, env=env
)

# Open a public tunnel to port 7860
!pip install -q pyngrok
from pyngrok import ngrok
# --- IMPORTANT: REPLACE "YOUR_NGROK_AUTH_TOKEN_HERE" WITH YOUR ACTUAL NGROK AUTH TOKEN ---
ngrok.set_auth_token("2waOEX4QPUHYMflNRcagUDVa6Qk_4uFUU5vW81nw6t3PZWR2T")
url = ngrok.connect(7860)
print("OPEN THIS:", url)

# Start the web UI (runs until you stop the cell)
!PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python tools/run_webui.py --llama-checkpoint-path checkpoints/s2-pro --decoder-checkpoint-path checkpoints/s2-pro/codec.pth --half

print(open('/content/webui.log').read())